### PR TITLE
space quest goodness

### PR DESCRIPTION
**Pull request by mshwery**

### CODE REVIEW

**Comment by mshwery** [comment]
also feel free to completely override this space. it's quite hacky.

**Comment by mshwery** [comment]
bwahahahahahaha.

**Comment by joeellis** [comment]
Was up working late last night so I didn't get a chance to look at this.  Will merge tonight

**Comment by mshwery** [comment]
you can merge this in. I'll probably do more with it later. @bhuga can also have at it.

**Pull request merged**
