### PR TITLE
Batman transition spinning logo

### PR DESCRIPTION
**Pull request by ericnormand**
Hit B

### CODE REVIEW

**Comment by joeellis** [comment]
Hahaha, oohhhh this project was definitely a good idea!

**Comment by bhuga** [comment]
This rather messes with our velociraptor, who is now covered by a batman logo....

also, i am getting this on the other animations:

XMLHttpRequest cannot load file://localhost/Users/ben/repos/barcamp2012/public/swing/script.js. Origin null is not allowed by Access-Control-Allow-Origin.

**Comment by joeellis** [comment]
Ahh yes, "B" is already bound on the raptorize one (it's activated by the konami code).  @ericnormand can you bind it to another key?

Also, @bhuga, that's only an issue in Chrome ATM, the script does some sort of local ajax call.  It works on the live site though.

**Comment by ericnormand** [comment]
Will rebind.

I think also the script needs to be reloaded. The url you showed is from before I reorganized the scripts.

**Pull request merged**
