### PR TITLE
added a few panes of sam and max, and used magnify js to zoom in on the rooms

### PR DESCRIPTION
**Pull request by mshwery**
FYI I didn't change the styles on `.tentacle` - I merely recompiled the sass.

### CODE REVIEW

**Comment by mshwery** [comment]
also more to come soon...

**Comment by joeellis** [comment]
Hehe that looks awesome, I haven't played that game in a long long time.  

BTW, can you do me a favor and pull from master and resolve whatever the conflict is?

**Comment by mshwery** [comment]
try that.

**Comment by joeellis** [comment]
This is pretty rad even though I feel a little pervy for peering into windows like that.

**Comment by bhuga** [comment]
the pull blinds arent working for me...

**Comment by mshwery** [comment]
not setup yet. just threw the img in there.

**Pull request merged**
