### PR TITLE
Burninating the city. Burninating the peasants.

### PR DESCRIPTION
**Pull request by jwietelmann**

### CODE REVIEW

**Comment by joeellis** [comment]
I was able to align Tayne to work right, but this one is not quite on the window for some reason.  Any idea what I'm missing?

**Comment by jwietelmann** [comment]
You mean the fire part? I was trying to make it look like it's coming up out of the window... idunnolol

**Comment by joeellis** [comment]
No, the alignment of the black box was off from the panel grid.  Didn't know if it was perhaps just me though and maybe I did a bad merge on somethin'

**Comment by joeellis** [comment]
I'll check it out tomorrow and see if I can figure out what's up

**Comment by jwietelmann** [comment]
This probably had something to do with the grid alignment, but either way it's gonna be easier to just redo it than to make this work now. I'm closing it.

**Comment by joeellis** [comment]
Yea, you might want to wait until I get the building with the transparent windows for it as well 

## 

Joe Ellis
Squarefour Digital Media
504.920.8248

**Pull request closed without merging**
