### PR TITLE
First pass on Ptero-Redactyl

### PR DESCRIPTION
**Pull request by togakangaroo**
ctrl+click to check it out

### CODE REVIEW

**Comment by EdwardReed** [comment]
Makes you right click on Mac!!!

**Comment by joeellis** [comment]
Was up working late last night so I didn't get a chance to look at this.  Will merge tonight!  If you can do me a favor though and do a pull from master and resolve the conflict, would be appreciated!

**Comment by joeellis** [comment]
This is absolutely beautiful.  So awesome.   I might actually bind it to something other than CTRL+Click because of the mac thing though, any objection?

**Comment by togakangaroo** [comment]
nope.all good
On Jun 12, 2012 8:13 PM, "Joe Ellis" <
reply@reply.github.com>
wrote:

**Pull request merged**
