### PR TITLE
Add file extensions

### PR DESCRIPTION
**Pull request by ericnormand**
If this doesn't fix the issue, it looks like it's a problem with the web server

The old link:
http://barcamp2012.herokuapp.com/swing/script

It should return some json.

New link:
http://barcamp2012.herokuapp.com/swing/script.js

Maybe it will work.

### CODE REVIEW

**Comment by joeellis** [comment]
Yea, this one doesn't look like it's working either.  It must be that Rack Static issue, sorry it's such a pain in the ass.

**Comment by ericnormand** [comment]
Don't worry about it. I just want to do something cool.

I just put in another pull request. I have never used rails, so I hope
it worked. I added "/swing" to the config.ru. I hope it works.

On Mon, Jun 4, 2012 at 10:52 PM, joeellis
reply@reply.github.com
wrote:

**Comment by joeellis** [comment]
Hahaha it worked, that is so damn sweet!!!!  I love it!!  Please contribute more if you've got time, you are clearly a chosen one.

Also, good to have the Rack issue, it means I should probably make it even easier and less error prone in the future.

**Comment by ericnormand** [comment]
Thanks! I'll add some more tomorrow. I've got some more ideas. and now
that I have the hang of it, it should go more smoothly.

On Mon, Jun 4, 2012 at 10:55 PM, joeellis
reply@reply.github.com
wrote:

**Comment by joeellis** [comment]
Yea, that was definitely a problem on our end, I'll see if I can't make that less of a pain in the ass... 

## 

Joe Ellis
Squarefour Digital Media
504.920.8248

**Pull request merged**
