### PR TITLE
add exploding dinosars, dog.

### PR DESCRIPTION
**Pull request by bhuga**
helps address issue #24

### CODE REVIEW

**Comment by joeellis** [comment]
Man, that dog really just does not know what he is doing

**Comment by bhuga** [comment]
he blows up, if it makes you feel better.

On Thu, Jun 7, 2012 at 1:59 PM, Joe Ellis <
reply@reply.github.com

**Comment by joeellis** [comment]
I saw that and had mixed feelings.  I felt he was just at the wrong place at the wrong time.

**Comment by bhuga** [comment]
actually just embarrassed myself laughing out loud.

On Thu, Jun 7, 2012 at 2:07 PM, Joe Ellis <
reply@reply.github.com

**Pull request merged**
