### PR TITLE
swinging zorro

### PR DESCRIPTION
**Pull request by ericnormand**
Try it out! Hit Z

### CODE REVIEW

**Comment by joeellis** [comment]
Hey Eric, I did a little reorganization for file stuffs because I was getting some errors.  I got rid of the errors, but still not seeing a zorro :(  What am I missing?  

https://github.com/joeellis/barcamp2012/tree/ericnormand-master

**Comment by ericnormand** [comment]
oh. It works in firefox, not chrome. give me a bit and i'll fix it

On Mon, Jun 4, 2012 at 6:26 PM, joeellis
reply@reply.github.com
wrote:

**Comment by ericnormand** [comment]
Ok. I figured out the problem. It's doing an ajax request, but can't
do it to file://  It has to be run from a server. Barring that, it
works in my chrome.

**Comment by joeellis** [comment]
Eric,

I saw it was making the call in firefox (I remember you have to launch Chrome with a special command to get it to do local file requests), but after pressing Z, I am still not seeing the animation :(  I might have missed something when I reorganized the files, but would you mind pulling down master and just taking a quick look?  I'm sure I'm missing something stupid that you'd spot right away after having worked on it.

I wanna see some zorro!!

**Comment by ericnormand** [comment]
I pulled down master and I can run it with no problem.

I ran chrome like this:  google-chrome --allow-file-access-from-files
public/index.html

If you scroll all the way to the top and hit 'z', there is a zorro.
Are there any error messages?

Eric

On Mon, Jun 4, 2012 at 7:27 PM, joeellis
reply@reply.github.com
wrote:

**Comment by joeellis** [comment]
Eric,

Weird, I launched it up to the site (http://barcamp2012.herokuapp.com/ <- don't pass this around yet please), but still am not seeing it in Chrome or Firefox.  Can you see it?  Is it just me?  If it's just me, then I'm not going to worry about it!

**Comment by ericnormand** [comment]
Hmm. I don't see it. I've got to eat dinner now, but I'll keep playing
with it. I'll keep you informed.

On Mon, Jun 4, 2012 at 8:18 PM, joeellis
reply@reply.github.com
wrote:

**Comment by joeellis** [comment]
No problem, anytime you can take a look.  Once I finish up my slides for tomorrow's presentation, I'll also take a look.   It bothers me greatly that there is this awesome zorro code and I'm totally missing out! 

## 

Joe Ellis
Squarefour Digital Media
504.920.8248

**Comment by ericnormand** [comment]
It looks like it's because the script (and image files) was not being
served correctly. I've added file extensions that may solve the
problem.

This is a json file: http://barcamp2012.herokuapp.com/swing/script,
but it looks like it's serving html when I do a get.

Anyway, maybe it's just because it has no extension. I've added a .js
extension and .png extensions to the images. That may help.

I'll put in a pull request.

Eric

On Mon, Jun 4, 2012 at 8:30 PM, joeellis
reply@reply.github.com
wrote:

**Comment by joeellis** [comment]
Ahh I know why now.  It's because Rack::Static is serving up only certain URLs:

https://github.com/joeellis/barcamp2012/blob/master/config.ru

Feel free to add any routes in there though that you want, or if you really want to, make it so it's not so hard-coded in like that.  I think that was taken from a blog and as it served it's purpose, but it doesn't have to be so restrictive

**Pull request merged**
