### PR TITLE
#49 Mobile Start

### PR DESCRIPTION
**Pull request by EdwardReed**
Ok guys, if you want to view the mobile version just resize your window... If your using chrome you won't be able to view the mobile version this way so use Safari when working on mobile. Also when you open the site in Safari bug #51 shows... just ignore it or <a href="https://github.com/joeellis/barcamp2012/issues/51">fix it</a>.

### CODE REVIEW

**Comment by EdwardReed** [comment]
Sorry about the dirty commit.. Cleaning it up now.

**Comment by EdwardReed** [comment]
Ok much better pull request.

**Comment by joeellis** [comment]
Sorry Eddie, this PR isn't being ignored, still hadn't gotten a good chance to look at it.  Will check it out at lunchtime tomororw!

**Comment by EdwardReed** [comment]
Ok cool beans!

**Pull request closed without merging**
